apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: react-k8s-raphaelcdsouza-com-tls
spec:
  secretName: react-k8s-raphaelcdsouza-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: react-k8s.raphaelcdsouza.com
  dnsNames:
    - react-k8s.raphaelcdsouza.com